Repository daejangjangi/daejangjangi-BE, pull requests merged in 2024-10, with the labels that each got.

#7 CI/CD 파이프 라인 구축 - 2
  .github/workflows/workflow.dev.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: enhancement

#8 dev 로그 활성화 및 application-dev.yml 수정
  src/main/resources/application-dev.yml
  src/main/resources/logback-spring.xml
Labels: bug

#10 로컬 회원가입 API 구현
  .github/workflows/workflow.dev.yml
  src/main/java/com/daejangjangi/backend/category/domain/entity/Category.java
  src/main/java/com/daejangjangi/backend/category/exception/NotManagedCategoryException.java
  src/main/java/com/daejangjangi/backend/category/exception/type/CategoryErrorType.java
  src/main/java/com/daejangjangi/backend/category/repository/CategoryRepository.java
  src/main/java/com/daejangjangi/backend/category/service/CategoryService.java
  src/main/java/com/daejangjangi/backend/disease/domain/entity/Disease.java
  src/main/java/com/daejangjangi/backend/disease/exception/NotManagedDiseaseException.java
  src/main/java/com/daejangjangi/backend/disease/exception/type/DiseaseErrorType.java
  src/main/java/com/daejangjangi/backend/disease/repository/DiseaseRepository.java
  src/main/java/com/daejangjangi/backend/disease/service/DiseaseService.java
  src/main/java/com/daejangjangi/backend/global/config/PasswordEncodeConfig.java
  src/main/java/com/daejangjangi/backend/global/config/SecurityConfig.java
  src/main/java/com/daejangjangi/backend/global/exception/ClientDataException.java
  src/main/java/com/daejangjangi/backend/global/exception/ForbiddenException.java
  src/main/java/com/daejangjangi/backend/global/exception/GlobalExceptionHandler.java
  src/main/java/com/daejangjangi/backend/global/exception/ServerDataException.java
  src/main/java/com/daejangjangi/backend/global/exception/UnAuthenticatedException.java
  src/main/java/com/daejangjangi/backend/global/exception/type/ApiGlobalErrorType.java
  src/main/java/com/daejangjangi/backend/global/response/ApiGlobalResponse.java
  src/main/java/com/daejangjangi/backend/member/controller/MemberController.java
  src/main/java/com/daejangjangi/backend/member/domain/dto/MemberRequestDto.java
  src/main/java/com/daejangjangi/backend/member/domain/dto/MemberResponseDto.java
  src/main/java/com/daejangjangi/backend/member/domain/entity/Member.java
  src/main/java/com/daejangjangi/backend/member/domain/entity/MemberCategory.java
  src/main/java/com/daejangjangi/backend/member/domain/entity/MemberDisease.java
  src/main/java/com/daejangjangi/backend/member/domain/enums/Role.java
  src/main/java/com/daejangjangi/backend/member/exception/EmailDuplicationException.java
  src/main/java/com/daejangjangi/backend/member/exception/NicknameDuplicationException.java
  src/main/java/com/daejangjangi/backend/member/exception/type/MemberErrorType.java
  src/main/java/com/daejangjangi/backend/member/repository/MemberCategoryRepository.java
  src/main/java/com/daejangjangi/backend/member/repository/MemberDiseaseRepository.java
  src/main/java/com/daejangjangi/backend/member/repository/MemberRepository.java
  src/main/java/com/daejangjangi/backend/member/service/MemberService.java
  src/main/resources/application-local.yml
  src/main/resources/format/intellij-java-google-style.xml
  src/main/resources/init.sql
  src/test/java/com/daejangjangi/backend/basic/BasicControllerTest.java
Labels: enhancement

#11 로컬 로그인 API 구현
  build.gradle
  src/main/java/com/daejangjangi/backend/basic/BasicController.java
  src/main/java/com/daejangjangi/backend/global/config/InterceptorConfig.java
  src/main/java/com/daejangjangi/backend/global/config/SecurityConfig.java
  src/main/java/com/daejangjangi/backend/global/config/SwaggerConfig.java
  src/main/java/com/daejangjangi/backend/global/config/token/TokenAuthInterceptor.java
  src/main/java/com/daejangjangi/backend/global/config/token/TokenAuthenticationFilter.java
  src/main/java/com/daejangjangi/backend/global/exception/ForbiddenException.java
  src/main/java/com/daejangjangi/backend/global/exception/GlobalExceptionHandler.java
  src/main/java/com/daejangjangi/backend/global/exception/type/ApiGlobalErrorType.java
  src/main/java/com/daejangjangi/backend/member/controller/MemberController.java
  src/main/java/com/daejangjangi/backend/member/domain/dto/MemberRequestDto.java
  src/main/java/com/daejangjangi/backend/member/domain/dto/MemberResponseDto.java
  src/main/java/com/daejangjangi/backend/member/domain/entity/Member.java
  src/main/java/com/daejangjangi/backend/member/exception/NotFoundMemberException.java
  src/main/java/com/daejangjangi/backend/member/exception/type/MemberErrorType.java
  src/main/java/com/daejangjangi/backend/member/repository/MemberRepository.java
  src/main/java/com/daejangjangi/backend/member/service/MemberService.java
  src/main/java/com/daejangjangi/backend/token/controller/TokenController.java
  src/main/java/com/daejangjangi/backend/token/domain/dto/TokenDto.java
  src/main/java/com/daejangjangi/backend/token/domain/dto/TokenRequestDto.java
  src/main/java/com/daejangjangi/backend/token/domain/entity/Token.java
  src/main/java/com/daejangjangi/backend/token/exception/ExpiredTokenException.java
  src/main/java/com/daejangjangi/backend/token/exception/InvalidJwtSignatureException.java
  src/main/java/com/daejangjangi/backend/token/exception/InvalidTokenException.java
  src/main/java/com/daejangjangi/backend/token/exception/NotAuthenticatedAccessException.java
  src/main/java/com/daejangjangi/backend/token/exception/type/TokenErrorType.java
  src/main/java/com/daejangjangi/backend/token/repository/TokenRepository.java
  src/main/java/com/daejangjangi/backend/token/service/AuthProvider.java
  src/main/java/com/daejangjangi/backend/token/service/TokenProvider.java
  src/main/java/com/daejangjangi/backend/token/service/TokenService.java
  src/main/java/com/daejangjangi/backend/token/service/TokenValidator.java
  src/test/java/com/daejangjangi/backend/basic/BasicControllerTest.java
  src/test/java/com/daejangjangi/backend/global/basic/ApplicationContextProvider.java
  src/test/java/com/daejangjangi/backend/global/basic/ContextLoadTest.java
  src/test/java/com/daejangjangi/backend/global/basic/ControllerTest.java
  src/test/java/com/daejangjangi/backend/global/basic/IntegrationTest.java
  src/test/java/com/daejangjangi/backend/global/basic/ServiceTest.java
  src/test/resources/application-test.yml
Labels: bug, enhancement

#15 MapStruct 도입
  build.gradle
  src/main/java/com/daejangjangi/backend/category/domain/entity/Category.java
  src/main/java/com/daejangjangi/backend/member/controller/MemberController.java
  src/main/java/com/daejangjangi/backend/member/domain/dto/MemberRequestDto.java
  src/main/java/com/daejangjangi/backend/member/domain/dto/MemberResponseDto.java
  src/main/java/com/daejangjangi/backend/member/domain/entity/Member.java
  src/main/java/com/daejangjangi/backend/member/domain/mapper/CategoriesMapper.java
  src/main/java/com/daejangjangi/backend/member/domain/mapper/DiseasesMapper.java
  src/main/java/com/daejangjangi/backend/member/domain/mapper/MemberMapper.java
  src/test/java/com/daejangjangi/backend/member/MemberMapperTest.java
Labels: enhancement

#18 게시글 생성, 수정 API 구현
  src/main/java/com/daejangjangi/backend/BackendApplication.java
  src/main/java/com/daejangjangi/backend/board/domain/entity/Board.java
  src/main/java/com/daejangjangi/backend/board/domain/entity/BoardPost.java
  src/main/java/com/daejangjangi/backend/board/repository/BoardPostRepository.java
  src/main/java/com/daejangjangi/backend/board/repository/BoardRepository.java
  src/main/java/com/daejangjangi/backend/board/service/BoardPostService.java
  src/main/java/com/daejangjangi/backend/board/service/BoardService.java
  src/main/java/com/daejangjangi/backend/global/common/BaseEntity.java
  src/main/java/com/daejangjangi/backend/global/config/JpaAuditingConfig.java
  src/main/java/com/daejangjangi/backend/post/controller/PostController.java
  src/main/java/com/daejangjangi/backend/post/domain/dto/PostRequestDto.java
  src/main/java/com/daejangjangi/backend/post/domain/dto/PostResponseDto.java
  src/main/java/com/daejangjangi/backend/post/domain/entity/Post.java
  src/main/java/com/daejangjangi/backend/post/domain/mapper/PostMapper.java
  src/main/java/com/daejangjangi/backend/post/exception/NotFoundPostException.java
  src/main/java/com/daejangjangi/backend/post/exception/NotManagedBoardException.java
  src/main/java/com/daejangjangi/backend/post/exception/NotPostAuthorException.java
  src/main/java/com/daejangjangi/backend/post/exception/type/PostErrorType.java
  src/main/java/com/daejangjangi/backend/post/repository/PostRepository.java
  src/main/java/com/daejangjangi/backend/post/service/PostService.java
  src/main/resources/init.sql
Labels: enhancement

#19 회원 관련 API Swagger 문서화
  .github/workflows/workflow.feat.yml
  src/main/java/com/daejangjangi/backend/basic/BasicApi.java
  src/main/java/com/daejangjangi/backend/basic/BasicController.java
  src/main/java/com/daejangjangi/backend/category/domain/Category.java
  src/main/java/com/daejangjangi/backend/disease/domain/Disease.java
  src/main/java/com/daejangjangi/backend/global/common/BaseEntity.java
  src/main/java/com/daejangjangi/backend/member/controller/MemberApi.java
  src/main/java/com/daejangjangi/backend/member/controller/MemberController.java
  src/main/java/com/daejangjangi/backend/member/domain/dto/MemberRequestDto.java
  src/main/java/com/daejangjangi/backend/member/domain/entity/Member.java
  src/main/java/com/daejangjangi/backend/member/domain/entity/MemberCategory.java
  src/main/java/com/daejangjangi/backend/member/domain/entity/MemberDisease.java
  src/main/java/com/daejangjangi/backend/social/controller/SocialApi.java
  src/main/java/com/daejangjangi/backend/social/controller/SocialController.java
  src/main/java/com/daejangjangi/backend/social/domain/dto/SocialRequestDto.java
  src/main/java/com/daejangjangi/backend/social/domain/entity/SocialAccount.java
  src/main/java/com/daejangjangi/backend/token/controller/TokenApi.java
  src/main/java/com/daejangjangi/backend/token/controller/TokenController.java
  src/main/java/com/daejangjangi/backend/token/domain/dto/TokenRequestDto.java
  src/main/java/com/daejangjangi/backend/token/domain/entity/Token.java
  src/main/java/com/daejangjangi/backend/token/service/TokenService.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/main/resources/init.sql
Labels: documentation

#21 회원 정보 수정 API 구현
  src/main/java/com/daejangjangi/backend/member/controller/MemberApi.java
  src/main/java/com/daejangjangi/backend/member/controller/MemberController.java
  src/main/java/com/daejangjangi/backend/member/domain/dto/MemberRequestDto.java
  src/main/java/com/daejangjangi/backend/member/domain/entity/Member.java
  src/main/java/com/daejangjangi/backend/member/domain/mapper/MemberMapper.java
  src/main/java/com/daejangjangi/backend/member/repository/MemberCategoryRepository.java
  src/main/java/com/daejangjangi/backend/member/repository/MemberDiseaseRepository.java
  src/main/java/com/daejangjangi/backend/member/service/MemberService.java
  src/main/java/com/daejangjangi/backend/social/domain/dto/SocialRequestDto.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/init.sql
Labels: bug, documentation, enhancement

#22 FAQ 관련 API 구현
  src/main/java/com/daejangjangi/backend/faq/controller/FaqApi.java
  src/main/java/com/daejangjangi/backend/faq/controller/FaqController.java
  src/main/java/com/daejangjangi/backend/faq/domain/dto/FaqRequestDto.java
  src/main/java/com/daejangjangi/backend/faq/domain/dto/FaqResponseDto.java
  src/main/java/com/daejangjangi/backend/faq/domain/entity/Faq.java
  src/main/java/com/daejangjangi/backend/faq/domain/enums/FaqCategory.java
  src/main/java/com/daejangjangi/backend/faq/domain/mapper/FaqMapper.java
  src/main/java/com/daejangjangi/backend/faq/exception/InvalidFaqCategoryException.java
  src/main/java/com/daejangjangi/backend/faq/exception/NotFoundFaqException.java
  src/main/java/com/daejangjangi/backend/faq/exception/type/FaqErrorType.java
  src/main/java/com/daejangjangi/backend/faq/repository/FaqRepository.java
  src/main/java/com/daejangjangi/backend/faq/service/FaqService.java
  src/main/java/com/daejangjangi/backend/faq/service/FaqValidator.java
  src/main/java/com/daejangjangi/backend/global/annotation/Response401WithSwagger.java
  src/main/java/com/daejangjangi/backend/global/annotation/Response403WithSwagger.java
  src/main/java/com/daejangjangi/backend/global/config/JpaAuditingConfig.java
  src/main/java/com/daejangjangi/backend/member/controller/MemberApi.java
  src/main/java/com/daejangjangi/backend/member/domain/entity/Member.java
  src/main/java/com/daejangjangi/backend/token/controller/TokenApi.java
Labels: bug, documentation, enhancement

#25 게시글 좋아요, 상세 조회 API 구현
  src/main/java/com/daejangjangi/backend/BackendApplication.java
  src/main/java/com/daejangjangi/backend/like/domain/entity/PostLike.java
  src/main/java/com/daejangjangi/backend/like/repository/PostLikeRepository.java
  src/main/java/com/daejangjangi/backend/like/service/PostLikeService.java
  src/main/java/com/daejangjangi/backend/post/controller/PostApi.java
  src/main/java/com/daejangjangi/backend/post/controller/PostController.java
  src/main/java/com/daejangjangi/backend/post/domain/dto/PostRequestDto.java
  src/main/java/com/daejangjangi/backend/post/domain/dto/PostResponseDto.java
  src/main/java/com/daejangjangi/backend/post/domain/entity/Post.java
  src/main/java/com/daejangjangi/backend/post/domain/mapper/BoardPostMapper.java
  src/main/java/com/daejangjangi/backend/post/domain/mapper/PostMapper.java
  src/main/java/com/daejangjangi/backend/post/exception/NotFoundPostException.java
  src/main/java/com/daejangjangi/backend/post/exception/NotPostAuthorException.java
  src/main/java/com/daejangjangi/backend/post/exception/type/PostErrorType.java
  src/main/java/com/daejangjangi/backend/post/repository/PostLockRepository.java
  src/main/java/com/daejangjangi/backend/post/service/PostService.java
  src/main/resources/init.sql
Labels: enhancement

#27 Swagger 관련 수정 사항
  src/main/java/com/daejangjangi/backend/basic/BasicApi.java
  src/main/java/com/daejangjangi/backend/category/service/CategoryService.java
  src/main/java/com/daejangjangi/backend/disease/service/DiseaseService.java
  src/main/java/com/daejangjangi/backend/faq/controller/FaqApi.java
  src/main/java/com/daejangjangi/backend/faq/controller/FaqController.java
  src/main/java/com/daejangjangi/backend/faq/domain/dto/FaqRequestDto.java
  src/main/java/com/daejangjangi/backend/faq/domain/dto/FaqResponseDto.java
  src/main/java/com/daejangjangi/backend/global/annotation/swagger/Response200WithSwagger.java
  src/main/java/com/daejangjangi/backend/global/annotation/swagger/Response401WithSwagger.java
  src/main/java/com/daejangjangi/backend/global/annotation/swagger/Response403WithSwagger.java
  src/main/java/com/daejangjangi/backend/global/annotation/swagger/ResponseCommonWithSwagger.java
  src/main/java/com/daejangjangi/backend/global/annotation/validation/EnumValidator.java
  src/main/java/com/daejangjangi/backend/global/annotation/validation/ValidEnum.java
  src/main/java/com/daejangjangi/backend/global/config/token/TokenAuthenticationFilter.java
  src/main/java/com/daejangjangi/backend/member/controller/MemberApi.java
  src/main/java/com/daejangjangi/backend/member/domain/dto/MemberRequestDto.java
  src/main/java/com/daejangjangi/backend/member/domain/dto/MemberResponseDto.java
  src/main/java/com/daejangjangi/backend/member/domain/entity/Member.java
  src/main/java/com/daejangjangi/backend/member/domain/mapper/MemberMapper.java
  src/main/java/com/daejangjangi/backend/social/controller/SocialApi.java
  src/main/java/com/daejangjangi/backend/social/controller/SocialController.java
  src/main/java/com/daejangjangi/backend/social/domain/SocialMapper.java
  src/main/java/com/daejangjangi/backend/social/domain/dto/SocialRequestDto.java
  src/main/java/com/daejangjangi/backend/social/domain/dto/SocialResponseDto.java
  src/main/java/com/daejangjangi/backend/social/service/SocialService.java
  src/main/java/com/daejangjangi/backend/token/controller/TokenApi.java
  src/main/java/com/daejangjangi/backend/token/domain/dto/TokenRequestDto.java
  src/main/java/com/daejangjangi/backend/token/domain/dto/TokenResponseDto.java
  src/main/java/com/daejangjangi/backend/token/service/AuthProvider.java
  src/main/java/com/daejangjangi/backend/token/service/TokenProvider.java
  src/main/java/com/daejangjangi/backend/token/service/TokenService.java
Labels: documentation

#29 [hotfix] sql init mode 수정
  src/main/resources/application-dev.yml
Labels: bug

#28 홈화면 > 카툰 등록 API 및 카툰 목록 조회 API 구현
  build.gradle
  src/main/java/com/daejangjangi/backend/daejangtoon/controller/DaejangtoonApi.java
  src/main/java/com/daejangjangi/backend/daejangtoon/controller/DaejangtoonController.java
  src/main/java/com/daejangjangi/backend/daejangtoon/domain/dto/DaejangtoonImageDto.java
  src/main/java/com/daejangjangi/backend/daejangtoon/domain/dto/DaejangtoonRequestDto.java
  src/main/java/com/daejangjangi/backend/daejangtoon/domain/dto/DaejangtoonResponseDto.java
  src/main/java/com/daejangjangi/backend/daejangtoon/domain/entity/Daejangtoon.java
  src/main/java/com/daejangjangi/backend/daejangtoon/domain/entity/DaejangtoonImage.java
  src/main/java/com/daejangjangi/backend/daejangtoon/domain/entity/DaejangtoonLike.java
  src/main/java/com/daejangjangi/backend/daejangtoon/domain/enums/Yoil.java
  src/main/java/com/daejangjangi/backend/daejangtoon/domain/mapper/DaejangtoonImageMapper.java
  src/main/java/com/daejangjangi/backend/daejangtoon/domain/mapper/DaejangtoonMapper.java
  src/main/java/com/daejangjangi/backend/daejangtoon/repository/DaejangtoonImageRepository.java
  src/main/java/com/daejangjangi/backend/daejangtoon/repository/DaejangtoonRepository.java
  src/main/java/com/daejangjangi/backend/daejangtoon/service/DaejangtoonService.java
  src/main/java/com/daejangjangi/backend/file/exception/EmptyFileException.java
  src/main/java/com/daejangjangi/backend/file/exception/NotImageFileException.java
  src/main/java/com/daejangjangi/backend/file/exception/NotSupportedFileFormatException.java
  src/main/java/com/daejangjangi/backend/file/exception/type/FileErrorType.java
  src/main/java/com/daejangjangi/backend/file/service/FileValidator.java
  src/main/java/com/daejangjangi/backend/file/service/S3Manager.java
  src/main/java/com/daejangjangi/backend/file/util/OrderConverter.java
  src/main/java/com/daejangjangi/backend/global/config/SecurityConfig.java
  src/main/java/com/daejangjangi/backend/global/config/multipart/MultipartJackson2HttpMessageConverter.java
  src/main/resources/application.yml
Labels: documentation, enhancement

#31 카툰 회차별 조회 API 및 최신 카툰 TOP1 조회 API 구현
  src/main/java/com/daejangjangi/backend/daejangtoon/controller/DaejangtoonApi.java
  src/main/java/com/daejangjangi/backend/daejangtoon/controller/DaejangtoonController.java
  src/main/java/com/daejangjangi/backend/daejangtoon/domain/dto/DaejangtoonResponseDto.java
  src/main/java/com/daejangjangi/backend/daejangtoon/domain/mapper/DaejangtoonMapper.java
  src/main/java/com/daejangjangi/backend/daejangtoon/repository/DaejangtoonRepository.java
  src/main/java/com/daejangjangi/backend/daejangtoon/service/DaejangtoonService.java
  src/test/java/com/daejangjangi/backend/daejangtoon/SortTest.java
Labels: documentation, enhancement

#33 [hotfix] 대장툰 관련 연관관계 수정 및 비지니스 로직 수정
  .github/workflows/workflow.feat.yml
  src/main/java/com/daejangjangi/backend/daejangtoon/controller/DaejangtoonApi.java
  src/main/java/com/daejangjangi/backend/daejangtoon/controller/DaejangtoonController.java
  src/main/java/com/daejangjangi/backend/daejangtoon/domain/dto/DaejangtoonRequestDto.java
  src/main/java/com/daejangjangi/backend/daejangtoon/domain/dto/DaejangtoonResponseDto.java
  src/main/java/com/daejangjangi/backend/daejangtoon/domain/entity/Daejangtoon.java
  src/main/java/com/daejangjangi/backend/daejangtoon/domain/entity/DaejangtoonChapter.java
  src/main/java/com/daejangjangi/backend/daejangtoon/domain/entity/DaejangtoonImage.java
  src/main/java/com/daejangjangi/backend/daejangtoon/domain/mapper/DaejangtoonMapper.java
  src/main/java/com/daejangjangi/backend/daejangtoon/exception/DaejangtoonErrorType.java
  src/main/java/com/daejangjangi/backend/daejangtoon/exception/NotFoundChapterException.java
  src/main/java/com/daejangjangi/backend/daejangtoon/repository/DaejangtoonChapterRepository.java
  src/main/java/com/daejangjangi/backend/daejangtoon/repository/DaejangtoonRepository.java
  src/main/java/com/daejangjangi/backend/daejangtoon/service/DaejangtoonChapterService.java
  src/main/java/com/daejangjangi/backend/daejangtoon/service/DaejangtoonService.java
  src/main/java/com/daejangjangi/backend/like/domain/entity/DaejangtoonLike.java
Labels: bug
