Repository daejangjangi/daejangjangi-BE, pull requests merged in 2024-11, with the labels that each got.

#35 대장툰 좋아요 등록/삭제 API 구현 및 조회수 증가 로직 추가
  src/main/java/com/daejangjangi/backend/daejangtoon/controller/DaejangtoonApi.java
  src/main/java/com/daejangjangi/backend/daejangtoon/controller/DaejangtoonController.java
  src/main/java/com/daejangjangi/backend/daejangtoon/domain/entity/DaejangtoonChapter.java
  src/main/java/com/daejangjangi/backend/daejangtoon/repository/DaejangtoonChapterRepository.java
  src/main/java/com/daejangjangi/backend/daejangtoon/service/DaejangtoonChapterService.java
  src/main/java/com/daejangjangi/backend/daejangtoon/service/DaejangtoonService.java
  src/main/java/com/daejangjangi/backend/file/service/S3Manager.java
  src/main/java/com/daejangjangi/backend/like/repository/DaejangtoonLikeRepository.java
  src/main/java/com/daejangjangi/backend/like/service/DaejangtoonLikeService.java
  src/test/java/com/daejangjangi/backend/daejangtoon/HitTest.java
Labels: documentation, enhancement

#38 게시글 조회 및 검색 API 구현
  src/main/java/com/daejangjangi/backend/board/controller/BoardApi.java
  src/main/java/com/daejangjangi/backend/board/controller/BoardController.java
  src/main/java/com/daejangjangi/backend/board/repository/BoardPostRepository.java
  src/main/java/com/daejangjangi/backend/board/repository/BoardRepository.java
  src/main/java/com/daejangjangi/backend/board/service/BoardService.java
  src/main/java/com/daejangjangi/backend/comment/domain/entity/PostComment.java
  src/main/java/com/daejangjangi/backend/comment/repository/PostCommentRepository.java
  src/main/java/com/daejangjangi/backend/comment/service/CommentService.java
  src/main/java/com/daejangjangi/backend/like/domain/entity/PostCommentLike.java
  src/main/java/com/daejangjangi/backend/post/controller/PostApi.java
  src/main/java/com/daejangjangi/backend/post/controller/PostController.java
  src/main/java/com/daejangjangi/backend/post/domain/dto/PostResponseDto.java
  src/main/java/com/daejangjangi/backend/post/domain/mapper/CommentMapper.java
  src/main/java/com/daejangjangi/backend/post/domain/mapper/PostMapper.java
  src/main/java/com/daejangjangi/backend/post/repository/PostCommentLikeRepository.java
  src/main/java/com/daejangjangi/backend/post/repository/PostCommentRepository.java
  src/main/java/com/daejangjangi/backend/post/repository/PostLikeRepository.java
  src/main/java/com/daejangjangi/backend/post/repository/PostRepository.java
  src/main/java/com/daejangjangi/backend/post/service/PostCommentLikeService.java
  src/main/java/com/daejangjangi/backend/post/service/PostCommentService.java
  src/main/java/com/daejangjangi/backend/post/service/PostLikeService.java
  src/main/java/com/daejangjangi/backend/post/service/PostService.java
Labels: enhancement

#40 회원탈퇴 API 구현
  src/main/java/com/daejangjangi/backend/comment/domain/entity/PostComment.java
  src/main/java/com/daejangjangi/backend/member/controller/MemberApi.java
  src/main/java/com/daejangjangi/backend/member/controller/MemberController.java
  src/main/java/com/daejangjangi/backend/member/domain/entity/Member.java
  src/main/java/com/daejangjangi/backend/member/service/MemberService.java
  src/main/java/com/daejangjangi/backend/post/domain/entity/Post.java
Labels: documentation, enhancement

#41 게시글 댓글 조회, 조회수, 삭제 API 구현
  src/main/java/com/daejangjangi/backend/board/controller/BoardController.java
  src/main/java/com/daejangjangi/backend/post/controller/PostApi.java
  src/main/java/com/daejangjangi/backend/post/controller/PostController.java
  src/main/java/com/daejangjangi/backend/post/domain/dto/PostResponseDto.java
  src/main/java/com/daejangjangi/backend/post/domain/mapper/PostMapper.java
  src/main/java/com/daejangjangi/backend/post/repository/DaejangtoonLikeRepository.java
  src/main/java/com/daejangjangi/backend/post/repository/PostRepository.java
  src/main/java/com/daejangjangi/backend/post/service/DaejangtoonLikeService.java
  src/main/java/com/daejangjangi/backend/post/service/PostService.java
Labels: enhancement

#42 문의하기 및 FAQ 관련 API 구현 및 수정
  src/main/java/com/daejangjangi/backend/faq/controller/FaqApi.java
  src/main/java/com/daejangjangi/backend/faq/controller/FaqController.java
  src/main/java/com/daejangjangi/backend/faq/domain/dto/FaqRequestDto.java
  src/main/java/com/daejangjangi/backend/faq/domain/dto/FaqResponseDto.java
  src/main/java/com/daejangjangi/backend/faq/domain/entity/Faq.java
  src/main/java/com/daejangjangi/backend/faq/domain/enums/FaqCategory.java
  src/main/java/com/daejangjangi/backend/faq/domain/mapper/FaqMapper.java
  src/main/java/com/daejangjangi/backend/faq/exception/QnaDuplicationException.java
  src/main/java/com/daejangjangi/backend/faq/exception/type/FaqErrorType.java
  src/main/java/com/daejangjangi/backend/faq/repository/FaqRepository.java
  src/main/java/com/daejangjangi/backend/faq/service/FaqService.java
  src/main/java/com/daejangjangi/backend/faq/service/FaqValidator.java
  src/main/java/com/daejangjangi/backend/member/domain/entity/Member.java
  src/main/java/com/daejangjangi/backend/member/exception/NotAuthorException.java
  src/main/java/com/daejangjangi/backend/member/exception/type/MemberErrorType.java
  src/main/java/com/daejangjangi/backend/member/service/MemberService.java
  src/main/java/com/daejangjangi/backend/qna/controller/QnaApi.java
  src/main/java/com/daejangjangi/backend/qna/controller/QnaController.java
  src/main/java/com/daejangjangi/backend/qna/domain/dto/QnaRequestDto.java
  src/main/java/com/daejangjangi/backend/qna/domain/dto/QnaResponseDto.java
  src/main/java/com/daejangjangi/backend/qna/domain/entity/Qna.java
  src/main/java/com/daejangjangi/backend/qna/domain/enums/QnaCategory.java
  src/main/java/com/daejangjangi/backend/qna/domain/enums/QnaStatus.java
  src/main/java/com/daejangjangi/backend/qna/domain/mapper/QnaMapper.java
  src/main/java/com/daejangjangi/backend/qna/exception/NotFoundQnaException.java
  src/main/java/com/daejangjangi/backend/qna/exception/type/QnaErrorType.java
  src/main/java/com/daejangjangi/backend/qna/repository/QnaRepository.java
  src/main/java/com/daejangjangi/backend/qna/service/QnaService.java
Labels: documentation, enhancement

#44 뉴스레터 관련 API 구현
  src/main/java/com/daejangjangi/backend/category/repository/CategoryRepository.java
  src/main/java/com/daejangjangi/backend/category/service/CategoryService.java
  src/main/java/com/daejangjangi/backend/daejangtoon/controller/DaejangtoonController.java
  src/main/java/com/daejangjangi/backend/daejangtoon/domain/dto/DaejangtoonResponseDto.java
  src/main/java/com/daejangjangi/backend/daejangtoon/domain/mapper/DaejangtoonMapper.java
  src/main/java/com/daejangjangi/backend/like/repository/DaejangtoonLikeRepository.java
  src/main/java/com/daejangjangi/backend/like/service/DaejangtoonLikeService.java
  src/main/java/com/daejangjangi/backend/member/domain/dto/MemberRequestDto.java
  src/main/java/com/daejangjangi/backend/newsletter/controller/NewsletterApi.java
  src/main/java/com/daejangjangi/backend/newsletter/controller/NewsletterController.java
  src/main/java/com/daejangjangi/backend/newsletter/domain/dto/NewsletterRequestDto.java
  src/main/java/com/daejangjangi/backend/newsletter/domain/dto/NewsletterResponseDto.java
  src/main/java/com/daejangjangi/backend/newsletter/domain/entity/Newsletter.java
  src/main/java/com/daejangjangi/backend/newsletter/domain/mapper/NewsletterMapper.java
  src/main/java/com/daejangjangi/backend/newsletter/exception/NotFoundNewsletterException.java
  src/main/java/com/daejangjangi/backend/newsletter/exception/type/NewsletterErrorType.java
  src/main/java/com/daejangjangi/backend/newsletter/repository/NewsletterRepository.java
  src/main/java/com/daejangjangi/backend/newsletter/service/NewsletterService.java
Labels: documentation, enhancement

#46 릴스 관련 API 구현
  src/main/java/com/daejangjangi/backend/cardnews/service/CardnewsService.java
  src/main/java/com/daejangjangi/backend/daejangtoon/service/DaejangtoonChapterService.java
  src/main/java/com/daejangjangi/backend/file/exception/NotAccessibleContentTypeException.java
  src/main/java/com/daejangjangi/backend/file/exception/NotVideoFileException.java
  src/main/java/com/daejangjangi/backend/file/exception/type/FileErrorType.java
  src/main/java/com/daejangjangi/backend/file/service/FileValidator.java
  src/main/java/com/daejangjangi/backend/newsletter/service/NewsletterService.java
  src/main/java/com/daejangjangi/backend/qna/controller/QnaApi.java
  src/main/java/com/daejangjangi/backend/reels/controller/ReelsApi.java
  src/main/java/com/daejangjangi/backend/reels/controller/ReelsController.java
  src/main/java/com/daejangjangi/backend/reels/domain/dto/ReelsRequestDto.java
  src/main/java/com/daejangjangi/backend/reels/domain/dto/ReelsResponseDto.java
  src/main/java/com/daejangjangi/backend/reels/domain/entity/Reels.java
  src/main/java/com/daejangjangi/backend/reels/domain/mapper/ReelsMapper.java
  src/main/java/com/daejangjangi/backend/reels/exception/NotFoundReelsException.java
  src/main/java/com/daejangjangi/backend/reels/exception/type/ReelsErrorType.java
  src/main/java/com/daejangjangi/backend/reels/repository/ReelsRepository.java
  src/main/java/com/daejangjangi/backend/reels/service/ReelsService.java
  src/main/resources/application.yml
Labels: bug, documentation, enhancement

#48 추천 상품 조회 API 구현
  src/main/java/com/daejangjangi/backend/cardnews/domain/entity/CardnewsImage.java
  src/main/java/com/daejangjangi/backend/daejangtoon/domain/entity/DaejangtoonImage.java
  src/main/java/com/daejangjangi/backend/file/service/FileValidator.java
  src/main/java/com/daejangjangi/backend/member/domain/dto/MemberRequestDto.java
  src/main/java/com/daejangjangi/backend/member/domain/dto/MemberResponseDto.java
  src/main/java/com/daejangjangi/backend/member/domain/entity/Agree.java
  src/main/java/com/daejangjangi/backend/member/domain/entity/Member.java
  src/main/java/com/daejangjangi/backend/member/service/MemberService.java
  src/main/java/com/daejangjangi/backend/newsletter/domain/dto/NewsletterRequestDto.java
  src/main/java/com/daejangjangi/backend/newsletter/domain/dto/NewsletterResponseDto.java
  src/main/java/com/daejangjangi/backend/newsletter/domain/entity/Newsletter.java
  src/main/java/com/daejangjangi/backend/product/controller/ProductApi.java
  src/main/java/com/daejangjangi/backend/product/controller/ProductController.java
  src/main/java/com/daejangjangi/backend/product/domain/dto/ProductRequestDto.java
  src/main/java/com/daejangjangi/backend/product/domain/dto/ProductResponseDto.java
  src/main/java/com/daejangjangi/backend/product/domain/entity/Discount.java
  src/main/java/com/daejangjangi/backend/product/domain/entity/Product.java
  src/main/java/com/daejangjangi/backend/product/domain/entity/ProductCategory.java
  src/main/java/com/daejangjangi/backend/product/domain/entity/ProductDisease.java
  src/main/java/com/daejangjangi/backend/product/domain/mapper/ProductMapper.java
  src/main/java/com/daejangjangi/backend/product/repository/ProductCategoryRepository.java
  src/main/java/com/daejangjangi/backend/product/repository/ProductDiseaseRepository.java
  src/main/java/com/daejangjangi/backend/product/repository/ProductRepository.java
  src/main/java/com/daejangjangi/backend/product/service/ProductService.java
  src/main/java/com/daejangjangi/backend/reels/domain/entity/Reels.java
Labels: documentation, enhancement

#50 인기 게시글 조회 및 회원 관심 게시판 조회, 수정 API 구현
  src/main/java/com/daejangjangi/backend/board/controller/BoardApi.java
  src/main/java/com/daejangjangi/backend/board/controller/BoardController.java
  src/main/java/com/daejangjangi/backend/board/domain/dto/BoardRequestDto.java
  src/main/java/com/daejangjangi/backend/board/domain/dto/BoardResponseDto.java
  src/main/java/com/daejangjangi/backend/board/domain/mapper/BoardMapper.java
  src/main/java/com/daejangjangi/backend/board/domain/mapper/MemberBoardMapper.java
  src/main/java/com/daejangjangi/backend/board/service/BoardPostService.java
  src/main/java/com/daejangjangi/backend/board/service/BoardService.java
  src/main/java/com/daejangjangi/backend/member/controller/MemberController.java
  src/main/java/com/daejangjangi/backend/member/domain/entity/Member.java
  src/main/java/com/daejangjangi/backend/member/domain/entity/MemberBoard.java
  src/main/java/com/daejangjangi/backend/member/repository/MemberBoardRepository.java
  src/main/java/com/daejangjangi/backend/member/service/MemberService.java
  src/main/java/com/daejangjangi/backend/post/controller/PostApi.java
  src/main/java/com/daejangjangi/backend/post/controller/PostController.java
  src/main/java/com/daejangjangi/backend/post/domain/dto/PostResponseDto.java
  src/main/java/com/daejangjangi/backend/post/domain/mapper/PostMapper.java
  src/main/java/com/daejangjangi/backend/post/repository/PostRepository.java
  src/main/java/com/daejangjangi/backend/post/service/PostService.java
Labels: enhancement

#53 회원 탈퇴 시, 게시글 엔티티 관련 삭제 기능 구현
  src/main/java/com/daejangjangi/backend/comment/domain/entity/PostComment.java
  src/main/java/com/daejangjangi/backend/member/service/MemberService.java
  src/main/java/com/daejangjangi/backend/post/controller/PostController.java
  src/main/java/com/daejangjangi/backend/post/domain/entity/Post.java
  src/main/java/com/daejangjangi/backend/post/domain/mapper/PostMapper.java
  src/main/java/com/daejangjangi/backend/post/repository/PostCommentLikeRepository.java
  src/main/java/com/daejangjangi/backend/post/repository/PostLikeRepository.java
  src/main/java/com/daejangjangi/backend/post/repository/PostRepository.java
Labels: enhancement

#55 상품 등록 시 관련 질병 또는 관심 태그 nullable 하도록 수정
  src/main/java/com/daejangjangi/backend/product/controller/ProductApi.java
  src/main/java/com/daejangjangi/backend/product/domain/dto/ProductRequestDto.java
  src/main/java/com/daejangjangi/backend/product/service/ProductService.java
Labels: bug

#57 게시글 목록 response dto 수정
  src/main/java/com/daejangjangi/backend/board/controller/BoardApi.java
  src/main/java/com/daejangjangi/backend/board/controller/BoardController.java
  src/main/java/com/daejangjangi/backend/post/controller/PostApi.java
  src/main/java/com/daejangjangi/backend/post/controller/PostController.java
  src/main/java/com/daejangjangi/backend/post/domain/dto/PostResponseDto.java
  src/main/java/com/daejangjangi/backend/post/domain/mapper/PostMapper.java
Labels: enhancement

#59 ERD 동기화
  src/main/java/com/daejangjangi/backend/daejangtoon/domain/entity/DaejangtoonChapter.java
  src/main/java/com/daejangjangi/backend/daejangtoon/domain/entity/DaejangtoonImage.java
  src/main/java/com/daejangjangi/backend/member/domain/entity/Member.java
  src/main/java/com/daejangjangi/backend/member/domain/entity/MemberDisease.java
  src/main/java/com/daejangjangi/backend/product/domain/entity/Product.java
  src/main/java/com/daejangjangi/backend/qna/domain/entity/Qna.java
Labels: wontfix

#61 마켓 - 상품 좋아요 등록/삭제 API 및 관심 상품 목록 조회 API 구현
  src/main/java/com/daejangjangi/backend/daejangtoon/domain/mapper/DaejangtoonMapper.java
  src/main/java/com/daejangjangi/backend/global/common/BaseEntity.java
  src/main/java/com/daejangjangi/backend/global/common/PageFields.java
  src/main/java/com/daejangjangi/backend/like/domain/entity/ProductLike.java
  src/main/java/com/daejangjangi/backend/like/repository/ProductLikeRepository.java
  src/main/java/com/daejangjangi/backend/like/service/ProductLikeService.java
  src/main/java/com/daejangjangi/backend/product/controller/ProductApi.java
  src/main/java/com/daejangjangi/backend/product/controller/ProductController.java
  src/main/java/com/daejangjangi/backend/product/domain/dto/ProductRequestDto.java
  src/main/java/com/daejangjangi/backend/product/domain/dto/ProductResponseDto.java
  src/main/java/com/daejangjangi/backend/product/domain/entity/Product.java
  src/main/java/com/daejangjangi/backend/product/domain/mapper/ProductMapper.java
  src/main/java/com/daejangjangi/backend/product/exception/NotFoundProductException.java
  src/main/java/com/daejangjangi/backend/product/exception/type/ProductErrorType.java
  src/main/java/com/daejangjangi/backend/product/service/ProductService.java
  src/main/resources/init.sql
Labels: documentation, enhancement

#62 fcm 푸시 알림 기능 구현
  .github/workflows/workflow.dev.yml
  build.gradle
  src/main/java/com/daejangjangi/backend/fcm/domain/entity/FcmToken.java
  src/main/java/com/daejangjangi/backend/fcm/repository/FcmTokenRepository.java
  src/main/java/com/daejangjangi/backend/fcm/service/FcmService.java
  src/main/java/com/daejangjangi/backend/global/config/FirebaseConfig.java
  src/main/java/com/daejangjangi/backend/notification/domain/entity/Notification.java
  src/main/java/com/daejangjangi/backend/notification/domain/enums/NotificationType.java
  src/main/java/com/daejangjangi/backend/notification/repository/NotificationRepository.java
  src/main/java/com/daejangjangi/backend/post/service/PostCommentService.java
  src/main/java/com/daejangjangi/backend/post/service/PostLikeService.java
Labels: enhancement

#65 상품 검색 API 구현
  build.gradle
  src/main/java/com/daejangjangi/backend/global/config/QueryDslConfig.java
  src/main/java/com/daejangjangi/backend/product/controller/ProductApi.java
  src/main/java/com/daejangjangi/backend/product/controller/ProductController.java
  src/main/java/com/daejangjangi/backend/product/domain/dto/DiscountRequestDto.java
  src/main/java/com/daejangjangi/backend/product/domain/dto/ProductResponseDto.java
  src/main/java/com/daejangjangi/backend/product/domain/entity/Discount.java
  src/main/java/com/daejangjangi/backend/product/domain/entity/Product.java
  src/main/java/com/daejangjangi/backend/product/domain/enums/ProductSortKey.java
  src/main/java/com/daejangjangi/backend/product/domain/mapper/DiscountMapper.java
  src/main/java/com/daejangjangi/backend/product/domain/mapper/ProductMapper.java
  src/main/java/com/daejangjangi/backend/product/repository/DiscountRepository.java
  src/main/java/com/daejangjangi/backend/product/service/ProductService.java
Labels: documentation, enhancement

#66 FCM 토큰 등록, 삭제 로직 기능 구현
  src/main/java/com/daejangjangi/backend/fcm/domain/dto/FcmRequestDto.java
  src/main/java/com/daejangjangi/backend/fcm/domain/entity/FcmToken.java
  src/main/java/com/daejangjangi/backend/fcm/repository/FcmTokenRepository.java
  src/main/java/com/daejangjangi/backend/fcm/service/FcmService.java
  src/main/java/com/daejangjangi/backend/global/config/SecurityConfig.java
  src/main/java/com/daejangjangi/backend/global/config/token/TokenAuthenticationFilter.java
  src/main/java/com/daejangjangi/backend/member/controller/MemberApi.java
  src/main/java/com/daejangjangi/backend/member/controller/MemberController.java
  src/main/java/com/daejangjangi/backend/member/domain/dto/MemberRequestDto.java
  src/main/java/com/daejangjangi/backend/post/service/PostCommentService.java
  src/main/java/com/daejangjangi/backend/post/service/PostLikeService.java
  src/test/java/com/daejangjangi/backend/global/basic/ControllerTest.java
Labels: enhancement

#67 로그인, 로그아웃 API와 FCM 토큰 등록, 삭제 API 분리
  src/main/java/com/daejangjangi/backend/fcm/controller/FcmApi.java
  src/main/java/com/daejangjangi/backend/fcm/controller/FcmController.java
  src/main/java/com/daejangjangi/backend/fcm/domain/dto/FcmRequestDto.java
  src/main/java/com/daejangjangi/backend/fcm/repository/FcmTokenRepository.java
  src/main/java/com/daejangjangi/backend/fcm/service/FcmService.java
  src/main/java/com/daejangjangi/backend/global/config/token/TokenAuthenticationFilter.java
  src/main/java/com/daejangjangi/backend/member/controller/MemberApi.java
  src/main/java/com/daejangjangi/backend/member/controller/MemberController.java
  src/main/java/com/daejangjangi/backend/member/domain/dto/MemberRequestDto.java
Labels: bug, enhancement

#68 상품 그룹별 조회 API 구현
  src/main/java/com/daejangjangi/backend/product/controller/ProductApi.java
  src/main/java/com/daejangjangi/backend/product/controller/ProductController.java
  src/main/java/com/daejangjangi/backend/product/domain/dto/ProductRequestDto.java
  src/main/java/com/daejangjangi/backend/product/domain/dto/ProductResponseDto.java
  src/main/java/com/daejangjangi/backend/product/domain/entity/Product.java
  src/main/java/com/daejangjangi/backend/product/domain/entity/ProductGroup.java
  src/main/java/com/daejangjangi/backend/product/domain/enums/ProductGroupEnum.java
  src/main/java/com/daejangjangi/backend/product/domain/mapper/ProductMapper.java
  src/main/java/com/daejangjangi/backend/product/exception/InvalidProductGroupException.java
  src/main/java/com/daejangjangi/backend/product/exception/type/ProductErrorType.java
  src/main/java/com/daejangjangi/backend/product/repository/ProductGroupRepository.java
  src/main/java/com/daejangjangi/backend/product/service/ProductService.java
Labels: bug, documentation, enhancement

#70 배변 일지 관련 API 구현
  src/main/java/com/daejangjangi/backend/stoollog/controller/StoollogAPI.java
  src/main/java/com/daejangjangi/backend/stoollog/controller/StoollogController.java
  src/main/java/com/daejangjangi/backend/stoollog/domain/dto/StoollogRequestDto.java
  src/main/java/com/daejangjangi/backend/stoollog/domain/dto/StoollogResponseDto.java
  src/main/java/com/daejangjangi/backend/stoollog/domain/entity/Stoollog.java
  src/main/java/com/daejangjangi/backend/stoollog/domain/enums/Color.java
  src/main/java/com/daejangjangi/backend/stoollog/domain/enums/Form.java
  src/main/java/com/daejangjangi/backend/stoollog/domain/mapper/StoollogMapper.java
  src/main/java/com/daejangjangi/backend/stoollog/exception/NotAuthorizedStoollogException.java
  src/main/java/com/daejangjangi/backend/stoollog/exception/NotFoundStoollogException.java
  src/main/java/com/daejangjangi/backend/stoollog/exception/type/StoollogErrorType.java
  src/main/java/com/daejangjangi/backend/stoollog/repository/StoollogRepository.java
  src/main/java/com/daejangjangi/backend/stoollog/service/StoollogService.java
Labels: enhancement

#72 FCM 관련 API 명 수정
  src/main/java/com/daejangjangi/backend/fcm/controller/FcmController.java
Labels: enhancement

#73 배너 관련 API & 대장간 상품 추천 API 구현
  src/main/java/com/daejangjangi/backend/banner/controller/BannerApi.java
  src/main/java/com/daejangjangi/backend/banner/controller/BannerController.java
  src/main/java/com/daejangjangi/backend/banner/domain/dto/BannerResponseDto.java
  src/main/java/com/daejangjangi/backend/banner/domain/entity/Banner.java
  src/main/java/com/daejangjangi/backend/banner/domain/mapper/BannerMapper.java
  src/main/java/com/daejangjangi/backend/banner/exception/AlreadyExistsBannerException.java
  src/main/java/com/daejangjangi/backend/banner/exception/type/BannerErrorType.java
  src/main/java/com/daejangjangi/backend/banner/repository/BannerRepository.java
  src/main/java/com/daejangjangi/backend/banner/service/BannerService.java
  src/main/java/com/daejangjangi/backend/global/config/SwaggerConfig.java
  src/main/java/com/daejangjangi/backend/product/controller/ProductApi.java
  src/main/java/com/daejangjangi/backend/product/controller/ProductController.java
  src/main/java/com/daejangjangi/backend/product/domain/dto/ProductResponseDto.java
  src/main/java/com/daejangjangi/backend/product/domain/mapper/ProductMapper.java
  src/main/java/com/daejangjangi/backend/product/repository/ProductRepository.java
  src/main/java/com/daejangjangi/backend/product/service/ProductService.java
Labels: documentation, enhancement

#74 [hotfix] 배너 조회관련 N+1 문제 해결(fetch)
  src/main/java/com/daejangjangi/backend/banner/repository/BannerRepository.java
  src/main/java/com/daejangjangi/backend/banner/service/BannerService.java
Labels: bug
