Repository daejangjangi/daejangjangi-BE, pull requests merged in 2024-12, with the labels that each got.

#75 최근 인기 상품 목록 조회 API 구현
  src/main/java/com/daejangjangi/backend/global/config/MongoConfig.java
  src/main/java/com/daejangjangi/backend/product/controller/ProductApi.java
  src/main/java/com/daejangjangi/backend/product/controller/ProductController.java
  src/main/java/com/daejangjangi/backend/product/domain/doc/ProductLookUpLog.java
  src/main/java/com/daejangjangi/backend/product/domain/dto/ProductLookUpLogDto.java
  src/main/java/com/daejangjangi/backend/product/domain/dto/ProductResponseDto.java
  src/main/java/com/daejangjangi/backend/product/domain/enums/LogType.java
  src/main/java/com/daejangjangi/backend/product/repository/ProductLogRepository.java
  src/main/java/com/daejangjangi/backend/product/repository/ProductRepository.java
  src/main/java/com/daejangjangi/backend/product/service/ProductService.java
  src/main/resources/application-local.yml
  src/main/resources/init.sql
Labels: documentation, enhancement

#76 배변 분석 API 구현
  build.gradle
  src/main/java/com/daejangjangi/backend/file/service/S3Manager.java
  src/main/java/com/daejangjangi/backend/global/config/OpenFeignConfig.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/controller/StoolanalysisApi.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/controller/StoolanalysisController.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/domain/dto/StoolanalysisRequestDto.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/domain/dto/StoolanalysisResponseDto.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/domain/entity/StoolDiagnosis.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/domain/entity/StoolImage.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/domain/enums/DietType.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/domain/enums/Mucus.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/domain/enums/ProteinLumps.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/domain/mapper/StoolDiagnosisMapper.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/openfeign/StoolanalysisOpenFeign.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/repository/StoolDiagnosisRepository.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/repository/StoolImageRepository.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/service/StoolanalysisService.java
Labels: enhancement

#78 배변 활동일 타임존 변경 / 배변 진단 응답 DTO 수정
  src/main/java/com/daejangjangi/backend/stoolanalysis/controller/StoolanalysisApi.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/controller/StoolanalysisController.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/domain/dto/StoolanalysisRequestDto.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/domain/dto/StoolanalysisResponseDto.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/domain/entity/StoolDiagnosis.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/domain/mapper/StoolDiagnosisMapper.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/openfeign/StoolanalysisOpenFeign.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/service/StoolanalysisService.java
  src/main/java/com/daejangjangi/backend/stoollog/domain/dto/StoollogRequestDto.java
  src/main/java/com/daejangjangi/backend/stoollog/domain/mapper/StoollogMapper.java
Labels: bug, enhancement

#80 [hotfix] 페이징 처리 관련 오류 수정
  src/main/java/com/daejangjangi/backend/product/service/ProductService.java
  src/main/resources/init.sql
Labels: bug

#81 [hotfix] 페이징 처리 후 정렬 관련 처리 추가
  src/main/java/com/daejangjangi/backend/product/service/ProductService.java
Labels: bug

#83 [hotfix] 중복 제거를 위해 group by 활용
  src/main/java/com/daejangjangi/backend/product/service/ProductService.java
  src/main/resources/init.sql
Labels: bug

#84 배변 분석 결과 목록 조회 및 삭제 API 구현 / 배변 분석 결과 저장 로직 수정
  src/main/java/com/daejangjangi/backend/stoolanalysis/controller/StoolanalysisApi.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/controller/StoolanalysisController.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/domain/dto/StoolanalysisRequestDto.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/domain/dto/StoolanalysisResponseDto.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/domain/entity/StoolDiagnosis.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/domain/entity/StoolImage.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/domain/mapper/StoolDiagnosisMapper.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/exception/NotFoundStoolDiagnosisException.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/exception/NotFoundStoolImageException.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/exception/UnauthorizedStoolException.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/exception/type/StoolanalysisErrorType.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/openfeign/StoolanalysisOpenFeign.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/repository/StoolDiagnosisRepository.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/repository/StoolImageRepository.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/service/StoolanalysisService.java
  src/main/java/com/daejangjangi/backend/stoollog/domain/dto/StoollogRequestDto.java
  src/main/java/com/daejangjangi/backend/stoollog/domain/mapper/StoollogMapper.java
  src/main/java/com/daejangjangi/backend/stoollog/service/StoollogService.java
Labels: bug, enhancement

#86 JVM 타임존 UTC로 설정
  src/main/java/com/daejangjangi/backend/BackendApplication.java
  src/main/java/com/daejangjangi/backend/post/controller/PostController.java
  src/main/java/com/daejangjangi/backend/post/domain/mapper/PostMapper.java
  src/main/java/com/daejangjangi/backend/post/service/PostService.java
Labels: bug

#88 타임존 KST로 통일
  src/main/java/com/daejangjangi/backend/BackendApplication.java
  src/main/java/com/daejangjangi/backend/post/domain/mapper/PostMapper.java
  src/main/java/com/daejangjangi/backend/post/service/PostService.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/domain/mapper/StoolDiagnosisMapper.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/service/StoolanalysisService.java
  src/main/java/com/daejangjangi/backend/stoollog/domain/mapper/StoollogMapper.java
  src/main/java/com/daejangjangi/backend/stoollog/service/StoollogService.java
Labels: bug

#89 docker-compose 내 mysql 타임존(KST) 설정 추가
  docker-compose.yml
Labels: bug

#91 배변 분석 세부 조회 API 구현
  src/main/java/com/daejangjangi/backend/stoolanalysis/controller/StoolanalysisApi.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/controller/StoolanalysisController.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/domain/dto/StoolanalysisResponseDto.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/domain/mapper/StoolDiagnosisMapper.java
  src/main/java/com/daejangjangi/backend/stoolanalysis/service/StoolanalysisService.java
Labels: enhancement
